FROM php:8.4-apache

RUN a2enmod rewrite

# Copy Xdebug config
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Enable SSL + Rewrite
RUN a2enmod ssl && a2enmod rewrite

# Generate self-signed cert
COPY generate-ssl.sh /generate-ssl.sh
RUN chmod +x /generate-ssl.sh && /generate-ssl.sh

# Replace the default site with SSL config
COPY default-ssl.conf /etc/apache2/sites-available/default-ssl.conf
RUN a2ensite default-ssl.conf
